version: "3"
services:
# SQLのサービス
 db:
   platform: linux/x86_64
   image: mysql:latest
   container_name: "spring_db"
   ports:
    - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: "root"
     MYSQL_DATABASE: "sample" # この場合sampleというデータベースが作成されます
     MYSQL_ROOT_USER: "root" # rootユーザーはパスワードを設定しないとエラーでます
     TZ: "Asia/Tokyo"
   volumes:
     - ./mysql/sql/:/docker-entrypoint-initdb.d
     - ./mysql/settings/:/var/lib/mysql
     - ./mysql/sql/mysql.cnf:/etc/mysql/conf.d/my.cnf

# springアプリケーションのサービス
 spring:
    platform: linux/x86_64
    image: openjdk:latest
    container_name: "spring"
    restart: always
    ports:
      - "9090:8080"
    tty: true
    depends_on:
      - db
    volumes:
      - ./my-workbook:/srv:cached
    working_dir: /srv
    environment:
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://db/sample"
      spring.datasource.username: "root"
      spring.datasource.password: "root"